/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopReceiptsRouteImport } from './routes/shop.receipts'
import { Route as ShopPosRouteImport } from './routes/shop.pos'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as ShopInventoryRouteImport } from './routes/shop.inventory'
import { Route as AdminReceiptsRouteImport } from './routes/admin.receipts'
import { Route as AdminMedicinesRouteImport } from './routes/admin.medicines'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopReceiptsRoute = ShopReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPosRoute = ShopPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopInventoryRoute = ShopInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShopRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicinesRoute = AdminMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/pos': typeof ShopPosRoute
  '/shop/receipts': typeof ShopReceiptsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/pos': typeof ShopPosRoute
  '/shop/receipts': typeof ShopReceiptsRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/medicines': typeof AdminMedicinesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/pos': typeof ShopPosRoute
  '/shop/receipts': typeof ShopReceiptsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/shop'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/dispatch'
    | '/admin/inventory'
    | '/admin/medicines'
    | '/admin/receipts'
    | '/shop/inventory'
    | '/shop/orders'
    | '/shop/pos'
    | '/shop/receipts'
    | '/admin/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/dispatch'
    | '/admin/inventory'
    | '/admin/medicines'
    | '/admin/receipts'
    | '/shop/inventory'
    | '/shop/orders'
    | '/shop/pos'
    | '/shop/receipts'
    | '/admin'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/shop'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/dispatch'
    | '/admin/inventory'
    | '/admin/medicines'
    | '/admin/receipts'
    | '/shop/inventory'
    | '/shop/orders'
    | '/shop/pos'
    | '/shop/receipts'
    | '/admin/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/receipts': {
      id: '/shop/receipts'
      path: '/receipts'
      fullPath: '/shop/receipts'
      preLoaderRoute: typeof ShopReceiptsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pos': {
      id: '/shop/pos'
      path: '/pos'
      fullPath: '/shop/pos'
      preLoaderRoute: typeof ShopPosRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/inventory': {
      id: '/shop/inventory'
      path: '/inventory'
      fullPath: '/shop/inventory'
      preLoaderRoute: typeof ShopInventoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicines': {
      id: '/admin/medicines'
      path: '/medicines'
      fullPath: '/admin/medicines'
      preLoaderRoute: typeof AdminMedicinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMedicinesRoute: typeof AdminMedicinesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMedicinesRoute: AdminMedicinesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopInventoryRoute: typeof ShopInventoryRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopPosRoute: typeof ShopPosRoute
  ShopReceiptsRoute: typeof ShopReceiptsRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopInventoryRoute: ShopInventoryRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopPosRoute: ShopPosRoute,
  ShopReceiptsRoute: ShopReceiptsRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
